### ISSUE TITLE
Encoding error "Invalid byte sequence in UTF-8"

### ISSUE THREAD

**Issue by praagyajoshi** [jdlubrano/stream_lines#43]
Hi @jdlubrano! 👋 
Thank you for the wonderful gem, it's been quite helpful for my use-case (which is streaming large JSONL files).
I'm running into an issue while streaming a particular file and I'm hoping for some help.

The exception raised is:
> **ArgumentError: invalid byte sequence in UTF-8**

The error occurs while trying to stream this particular file:

> https://github.com/praagyajoshi/dummy-repo/blob/master/bulk-9607413898.jsonl

The source of the file is somewhere else but I've uploaded to a demo repo for easy reproduction.

Interestingly enough, while streaming the file from the original URL, I was getting a slightly different exception "**<Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8>**" at https://github.com/jdlubrano/stream_lines/blob/main/lib/stream_lines/reading/stream.rb#L45.

I'm by no means an expert on encoding, but will be happy to provide any info needed.

Here is the backtrace of the exception:
```
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:41:in `split'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:41:in `extract_lines'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:32:in `block in stream_lines'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty/request.rb:152:in `block (2 levels) in perform'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:433:in `call_block'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:424:in `<<'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:383:in `block (2 levels) in inflate_adapter'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:382:in `inflate'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:382:in `block in inflate_adapter'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:433:in `call_block'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:424:in `<<'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:124:in `read'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:404:in `read'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:293:in `block in read_body_0'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:264:in `inflater'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:283:in `read_body_0'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:204:in `read_body'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty/request.rb:149:in `block in perform'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1503:in `block in transport_request'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:165:in `reading_body'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1502:in `transport_request'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1464:in `request'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:910:in `start'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1455:in `request'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty/request.rb:145:in `perform'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty.rb:594:in `perform_request'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty.rb:508:in `get'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:31:in `stream_lines'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:21:in `each'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/json_lines.rb:18:in `each'",
```

Thank you again for the help!

**Comment by praagyajoshi** [comment]
With some more tinkering, I found that streaming the file works if encoding is forced to `UTF-8` with the `replace` option set for invalid and undefined characters:
```ruby
def extract_lines(chunk)
  # Force encoding to UTF-8 and replace all invalid and undefined characters
  # to avoid raising an invalid byte sequence error
  encoded_chunk = chunk.encode('utf-8', :invalid => :replace, :undef => :replace)
  lines = encoded_chunk.split($INPUT_RECORD_SEPARATOR, -1)

  if lines.length > 1
    @buffer.rewind
    r = @buffer.read
    lines.first.prepend(r)
    @buffer = StringIO.new
  end

  @buffer << lines.pop
  lines
end
```

**Comment by jdlubrano** [comment]
Hi @praagyajoshi .  Sorry for a delayed response.  Thank you for the detailed stack trace and for providing an example file.  Unfortunately I don't think that I have time to look into this today 😞 .  Let me dive into it tomorrow and get back to you.

**Comment by jdlubrano** [comment]
I had a meeting get canceled and took the opportunity to check this now 🎉 .  Playing around in my console, I found that using `chunk.force_encoding('utf-8')` retained the ™ and copyright characters.  Would you mind trying out `force_encoding` to see if it fixes your issue?  If it does, I will have to think about the best way to accommodate different encodings in this gem.  I am currently leaning towards the most flexible approach and allowing users to insert their own pre-processing hooks.  So something like:

```ruby
stream = StreamLines::Reading::Stream.new(url, preprocess_chunk: -> (chunk) { chunk.force_encoding('utf-8') })
```

There would be more user-friendly implementations if the solution were to be encoding-specific; however, the lamba/Proc approach provides the most flexibility.

Something like

```ruby
StreamLines::Reading::Stream.new(url, force_encoding: 'utf-8')
```

would work, but it is limiting 🤔 .

**Comment by praagyajoshi** [comment]
Thank you so much for looking into this @jdlubrano!
I actually did try out `chunk.force_encoding('utf-8')` earlier but it was still raising "invalid byte sequence in UTF-8" exception for me.
```
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-327e36b0bf41/lib/stream_lines/reading/stream.rb:57:in `split'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-327e36b0bf41/lib/stream_lines/reading/stream.rb:57:in `extract_lines'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-327e36b0bf41/lib/stream_lines/reading/stream.rb:32:in `block in stream_lines'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty/request.rb:152:in `block (2 levels) in perform'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:433:in `call_block'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:424:in `<<'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:124:in `read'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:293:in `block in read_body_0'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:278:in `inflater'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:283:in `read_body_0'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:204:in `read_body'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty/request.rb:149:in `block in perform'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1503:in `block in transport_request'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:165:in `reading_body'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1502:in `transport_request'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1464:in `request'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:910:in `start'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1455:in `request'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty/request.rb:145:in `perform'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty.rb:594:in `perform_request'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty.rb:508:in `get'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-327e36b0bf41/lib/stream_lines/reading/stream.rb:31:in `stream_lines'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-327e36b0bf41/lib/stream_lines/reading/stream.rb:21:in `each'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-327e36b0bf41/lib/stream_lines/reading/json_lines.rb:18:in `each'
```

What ended up working for me was a sort of double encoding pass:
https://github.com/praagyajoshi/stream_lines/blob/feat/force-utf8-encoding/lib/stream_lines/reading/stream.rb#L41-L69
I know this isn't elegant at all, but it was the only way for me to be sure that no exceptions were raised and the data was formatted properly.

As for your comment about adding pre-processing hooks, it certainly sounds interesting and could be quite useful to a bunch of folks, I bet.
However, on the other hand, passing an (optional) encoding is also quite a relevant option and can be more easily implemented I believe.

**Comment by jdlubrano** [comment]
Given that this is intermittent, which I can only guess has to do with where the server is chunking the streams, I need to think a bit about what we should do when we encounter an invalid byte sequence.  I am wondering if we should go and get the next chunk.  Hoping that the last part of the chunk that throws the invalid byte sequence error and the first part of the next chunk combine to create a valid byte sequence.  I really don't know if that will work, though 🤔 .

**Comment by jdlubrano** [comment]
Ah!  When I was debugging, I happened to notice that a chunk that threw an error was in fact split on the ü character.  What I saw when debugging the chunk was `Select Garmin N?` when the original text was `Select Garmin Nüvi GPS`.
